alter table MYCABINET_REQUEST_ATTACHMENT_LINK add constraint FK_REQATT_REQUEST foreign key (REQUEST_ID) references MYCABINET_REQUEST(ID);
alter table MYCABINET_REQUEST_ATTACHMENT_LINK add constraint FK_REQATT_ATTACHMENT foreign key (ATTACHMENT_ID) references MYCABINET_ATTACHMENT(ID);
