alter table MYCABINET_RESPONSE add constraint FK_MYCABINET_RESPONSE_REQUEST foreign key (REQUEST_ID) references MYCABINET_REQUEST(ID);
create index IDX_MYCABINET_RESPONSE_REQUEST on MYCABINET_RESPONSE (REQUEST_ID);
