alter table MYCABINET_RESPONSE_FILE_DESCRIPTOR_LINK add constraint FK_RESFILDES_RESPONSE foreign key (RESPONSE_ID) references MYCABINET_RESPONSE(ID);
alter table MYCABINET_RESPONSE_FILE_DESCRIPTOR_LINK add constraint FK_RESFILDES_FILE_DESCRIPTOR foreign key (FILE_DESCRIPTOR_ID) references SYS_FILE(ID);
