alter table MYCABINET_RESPONSE add constraint FK_MYCABINET_RESPONSE_CREATOR foreign key (CREATOR_ID) references SEC_USER(ID);
create index IDX_MYCABINET_RESPONSE_CREATOR on MYCABINET_RESPONSE (CREATOR_ID);
