alter table MYCABINET_REQUEST add constraint FK_MYCABINET_REQUEST_CREATOR foreign key (CREATOR_ID) references SEC_USER(ID);
create index IDX_MYCABINET_REQUEST_CREATOR on MYCABINET_REQUEST (CREATOR_ID);
